# Generated by Django 3.1.7 on 2021-06-07 08:11

import articles.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20210527_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=articles.models.upload_location),
        ),
    ]
